Iter9
yogip/metrics pull request #10
Opened 2024-05-26 11:25 UTC by yogip

2024-06-03 21:02 UTC, avhitrov requested changes
Не смог скомпилировать и запустить сервер под ОС Windows из-за кривой библиотеки, не поддерживающей возможность такой сборки. Подробности - в комментарии к коду. Предлагаю для реализации необходимого функционала либо использовать ванильный Go, либо более аккуратно написанную библиотеку.

2024-06-03 21:02 UTC, avhitrov commented on internal/infra/api/rest/rest.go
> +	"github.com/fvbock/endless"
Данная либа написана криво и не поддерживает возможность компиляции в ОС Windows. При попытке собрать проект, компилятор падает:
```
PS C:\work\src\github.com\yogip\metrics> go build .\cmd\server\
# github.com/fvbock/endless
C:\Users\Khitrov_An\go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:64:11: undefined: syscall.SIGUSR1
C:\Users\Khitrov_An\go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:65:11: undefined: syscall.SIGUSR2
C:\Users\Khitrov_An\go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:68:11: undefined: syscall.SIGTSTP
C:\Users\Khitrov_An\go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:111:13: undefined: syscall.SIGUSR1
C:\Users\Khitrov_An\go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:112:13: undefined: syscall.SIGUSR2
C:\Users\Khitrov_An\go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:115:13: undefined: syscall.SIGTSTP
C:\Users\Khitrov_An\go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:119:13: undefined: syscall.SIGUSR1
C:\Users\Khitrov_An\go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:120:13: undefined: syscall.SIGUSR2
C:\Users\Khitrov_An\go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:123:13: undefined: syscall.SIGTSTP
C:\Users\Khitrov_An\go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:224:11: undefined: syscall.Kill
C:\Users\Khitrov_An\go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:224:11: too many errors
```

2024-06-04 06:17 UTC, yogip commented on internal/infra/api/rest/rest.go
> +	"github.com/fvbock/endless"
Переделал на ванильный Go

2024-06-05 22:55 UTC, avhitrov requested changes
Наконец смог нормально потестировать и детально ознакомиться с кодом. Впечатление очень хорошее, но есть несколько несовместимых с аппрувом ошибок реализации:
1. Неверный приоритет опроса параметров конфигурации
2. Выставление синхронной записи (`-i=0`) приводит к невохможности нормально погасить сервер.
3. Отключение записи в файл (`-f=""`) приводит к падению сервера на этапе конфигурации. А должно - к отключению функции чтения-записи в файл.

Все в комментариях к коду. Прошу не резолвить мои комментарии, я по ним проверяю работу над замечаниями.

2024-06-05 22:55 UTC, avhitrov commented on internal/core/config/config.go
> +	}
В соответствии с ТЗ приоритет должны иметь переменные окружения. При этом необходимо очень аккуратно обходиться с умолчаниями. В частности, должна остаться возможность выставить по умолчанию (аргументом командной строки, по-другому не получится) пустое значение для имени файла. В идеале алгоритм такой (на примере имени файла):
```
flag.StringVar(&cfg.Storage.FileStoragePath, "f", "/tmp/metrics-db.json", "Path to dump file")
flag.Parse()
if value, exists := os.GetEnv("FILE_STORAGE_PATH"); exists {
    cfg.Storage.FileStoragePath = value
}
```

2024-06-05 22:55 UTC, avhitrov commented on internal/core/model/counter.go
> +func (c *Counter) Incremet(value int64) error {
```suggestion
func (c *Counter) Increment(value int64) error {
```

2024-06-05 22:55 UTC, avhitrov commented on internal/infra/store/memory/store.go
> +	s.quit <- true
Если интервал сохранения указан равным нулю (синхронное сохранение), то у этого канала не находится читатель. В итоге по Ctrl-C сервер не завершает работу (под виндой абсолютно точно). Можно только жестко кильнуть его. Решение - либо закрывать канал, а не кидать в него значение, либо добавить проверку.

2024-06-05 22:55 UTC, avhitrov commented on cmd/server/main.go
> +	store, err := store.NewStore(&cfg.Storage)
Ситуация, когда путь к файлу не указан (пустая строка) описан в ТЗ и не должен приводить к ошибке. В этом случае просто отключаются функции чтения и записи в файл, сервер откатывается на in-memory модель.

2024-06-09 22:05 UTC, avhitrov approved these changes
Все замечания исправлены.

2024-06-10 02:26 UTC, merged